version: "3"
virtualmachines:
- name: k8s
  image: instruqt/k3s-v1-33-4
  environment:
    IS_OPENSHIFT_CLUSTER: "n"
    NR_SUBACCOUNT_NAME_PREFIX: 'MARS - '
    INSTRUCTOR_EMAIL_HANDLE: dgomezblanco
    INSTRUCTOR_EMAIL_DOMAIN: newrelic.com
    TF_AUTO_APPROVE: "true"
    TF_VAR_admin_group_name: Admin
    TF_VAR_app_name: frontend
    TF_VAR_newrelic_parent_account_id: "6879196"
    TF_VAR_readonly_role_name: all_product_admin
  machine_type: n2-standard-4
secrets:
- name: MARS_PARENT_API_KEY
